[project]
name = "means_of_production"
version = "0.1.0"
description = "Means of Production library"
authors = [
    {name = "Matty Roses", email = "admin@meansofp.org"},
]
dependencies = [
    "pydantic>=2.10.4",
    "email-validator>=2.1.1",
]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pytest.ini_options]
markers = [
    "ignore: marks tests to be ignored",
]

[tool.ruff.lint]
# Enable import sorting (I) by default
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
# ignore type annotation errors in test files
"**/tests/**/*.py" = ["ANN"]
"conftest.py" = ["ANN"]
"__init__.py" = ["F401"]

[dependency-groups]
dev = [
    "pytest-cov>=6.2.1",
    "pytest>=8.3.4",
    "black>=24.10.0",
    "ruff>=0.8.4",
    "pyright>=1.1.391",
    "pytest-asyncio>=1.0.0",
    "freezegun>=1.5.2",
]
