# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-07-31T15:01:04+00:00

from __future__ import annotations

from typing import Annotated, Optional, Union
from uuid import UUID

from fastapi import FastAPI, HTTPException
from pydantic import conint

from server.models import (
    DistributedLibrary,
    SimpleLibrary,
    Status1,
    Thing,
    ThingsGetResponse,
    ThingsSearchSearchTermGetResponse,
)

app = FastAPI(
    title="MeansOfProduction API",
    description="This server allows clients to use the MeansOfProduction protocol and servers.  MeansOfProduction\npowers libraries, both traditional and virtual/distributed, as well as allowing cross functionality\nbetween other supported platforms.\n\nSome useful links:\n- [Project Site](https://meansofpo.org)",
    termsOfService="https://swagger.io/terms/",
    contact={"email": "admin@meansofp.org"},
    license={"name": "MIT"},
    version="0.0.1",
    servers=[{"url": "https://meansofp.org/api/v1"}],
)


@app.get(
    "/library",
    response_model=None,
    responses={"200": {"model": list[SimpleLibrary | DistributedLibrary]}},
    tags=["library"],
)
def get_library(
    active: bool = True,
    max_items: Annotated[int, conint(ge=1, le=100)] = 20,
    skip: Annotated[int, conint(ge=0)] = 0,
) -> list[SimpleLibrary | DistributedLibrary]:
    raise NotImplementedError()


@app.post(
    "/library",
    response_model=None,
    responses={
        "200": {"model": SimpleLibrary | DistributedLibrary},
        "409": {"model": None},
    },
    tags=["library"],
)
def post_library(
    body: SimpleLibrary | DistributedLibrary,
) -> SimpleLibrary | DistributedLibrary:
    """
    creates a new simple library
    """
    raise NotImplementedError()


@app.get(
    "/library/{library_id}",
    response_model=None,
    responses={"200": {"model": SimpleLibrary | DistributedLibrary}},
    tags=["library"],
)
def get_library_library_id(library_id: UUID) -> SimpleLibrary | DistributedLibrary:
    raise NotImplementedError()


@app.put(
    "/library/{library_id}",
    response_model=None,
    responses={"200": {"model": SimpleLibrary | DistributedLibrary}},
    tags=["library"],
)
def put_library_library_id(library_id: UUID) -> SimpleLibrary | DistributedLibrary:
    raise NotImplementedError()


@app.get(
    "/library/{library_id}/things",
    response_model=None,
    responses={"200": {"model": list[Thing]}},
    tags=["inventory", "library"],
)
def get_library_library_id_things(
    library_id: UUID, status: Status1 | None = None
) -> list[Thing]:
    raise NotImplementedError()


@app.get(
    "/library/{library_id}/things/{thing_id}",
    response_model=None,
    responses={"200": {"model": Thing}},
    tags=["inventory", "library"],
)
def get_library_library_id_things_thing_id(
    library_id: UUID, thing_id: UUID, status: Status1 | None = None
) -> Thing:
    raise NotImplementedError()


@app.put(
    "/library/{library_id}/things/{thing_id}",
    response_model=None,
    responses={"200": {"model": Thing}},
    tags=["inventory", "library"],
)
def put_library_library_id_things_thing_id(
    library_id: UUID, thing_id: UUID, body: Thing | None = None
) -> Thing | None:
    pass


@app.get(
    "/things",
    response_model=None,
    responses={"200": {"model": ThingsGetResponse}},
    tags=["inventory"],
)
def get_things(
    status: Status1 | None = None, max_distance: Optional[float] = None
) -> Optional[ThingsGetResponse]:
    pass


@app.get(
    "/things/search/{search_term}",
    response_model=None,
    responses={"200": {"model": ThingsSearchSearchTermGetResponse}},
    tags=["inventory", "search"],
)
def get_things_search_search_term(
    search_term: str, status: Status1 | None = None
) -> Optional[ThingsSearchSearchTermGetResponse]:
    pass
