# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-07-31T15:01:04+00:00

from __future__ import annotations

from typing import Optional, Union
from uuid import UUID

from fastapi import FastAPI
from pydantic import conint

from .models import (
    LibraryGetResponse,
    LibraryLibraryIdGetResponse,
    LibraryLibraryIdPutResponse,
    LibraryLibraryIdThingsGetResponse,
    LibraryPostResponse,
    SimpleLibrary,
    Status1,
    Thing,
    ThingsGetResponse,
    ThingsSearchSearchTermGetResponse,
)

app = FastAPI(
    title='MeansOfProduction API',
    description='This server allows clients to use the MeansOfProduction protocol and servers.  MeansOfProduction\npowers libraries, both traditional and virtual/distributed, as well as allowing cross functionality\nbetween other supported platforms.\n\nSome useful links:\n- [Project Site](https://meansofpo.org)',
    termsOfService='https://swagger.io/terms/',
    contact={'email': 'admin@meansofp.org'},
    license={'name': 'MIT'},
    version='0.0.1',
    servers=[{'url': 'https://meansofp.org/api/v1'}],
)


@app.get(
    '/library',
    response_model=None,
    responses={'200': {'model': LibraryGetResponse}},
    tags=['library'],
)
def get_library(
    active: Optional[bool] = True,
    max_items: Optional[conint(ge=1, le=100)] = 20,
    skip: Optional[conint(ge=0)] = 0,
) -> Optional[LibraryGetResponse]:
    pass


@app.post(
    '/library',
    response_model=None,
    responses={
        '200': {'model': LibraryPostResponse},
        '409': {'model': LibraryPostResponse1},
    },
    tags=['library'],
)
def post_library(
    body: Union[SimpleLibrary, DistributedLibrary],
) -> Optional[Union[LibraryPostResponse, LibraryPostResponse1]]:
    """
    creates a new simple library
    """
    pass


@app.get(
    '/library/{library_id}',
    response_model=None,
    responses={'200': {'model': LibraryLibraryIdGetResponse}},
    tags=['library'],
)
def get_library_library_id(library_id: UUID) -> Optional[LibraryLibraryIdGetResponse]:
    pass


@app.put(
    '/library/{library_id}',
    response_model=None,
    responses={'200': {'model': LibraryLibraryIdPutResponse}},
    tags=['library'],
)
def put_library_library_id(library_id: UUID) -> Optional[LibraryLibraryIdPutResponse]:
    pass


@app.get(
    '/library/{library_id}/things',
    response_model=None,
    responses={'200': {'model': LibraryLibraryIdThingsGetResponse}},
    tags=['inventory', 'library'],
)
def get_library_library_id_things(
    library_id: UUID, status: Optional[Status1] = None
) -> Optional[LibraryLibraryIdThingsGetResponse]:
    pass


@app.get(
    '/library/{library_id}/things/{thing_id}',
    response_model=None,
    responses={'200': {'model': Thing}},
    tags=['inventory', 'library'],
)
def get_library_library_id_things_thing_id(
    library_id: UUID, thing_id: UUID = ..., status: Optional[Status1] = None
) -> Optional[Thing]:
    pass


@app.put(
    '/library/{library_id}/things/{thing_id}',
    response_model=None,
    responses={'200': {'model': Thing}},
    tags=['inventory', 'library'],
)
def put_library_library_id_things_thing_id(
    library_id: UUID, thing_id: UUID = ..., body: Thing = None
) -> Optional[Thing]:
    pass


@app.get(
    '/things',
    response_model=None,
    responses={'200': {'model': ThingsGetResponse}},
    tags=['inventory'],
)
def get_things(
    status: Optional[Status1] = None, max_distance: Optional[float] = None
) -> Optional[ThingsGetResponse]:
    pass


@app.get(
    '/things/search/{search_term}',
    response_model=None,
    responses={'200': {'model': ThingsSearchSearchTermGetResponse}},
    tags=['inventory', 'search'],
)
def get_things_search_search_term(
    search_term: str, status: Optional[Status1] = None
) -> Optional[ThingsSearchSearchTermGetResponse]:
    pass
