from enum import Enum


class LoanStatus(Enum):
    STARTED = "STARTED"
    BORROW = "BORROWED"
    OVERDUE = "OVERDUE"
    WAITING_ON_LENDER_ACCEPTANCE = "WAITING_ON_LENDER_ACCEPTANCE"
    RETURNED_DAMAGED = "RETURNED_DAMAGED"
    RETURNED = "RETURNED"
